<a href="https://colab.research.google.com/github/ParveenDavid2394/Tensorflow/blob/master/Module2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.6/dist-packages/tensorflow/_api/v2/version/__init__.py'>


## Datatype of tf variables

In [3]:
string = tf.Variable('This is a string', tf.string)
number = tf.Variable(12, tf.int16)
float_tf = tf.Variable(13.45, tf.float32)

## Rank/Degree

number of dimensions involved in the tensor.
Example above are scalar with 0 rank/degree.
Example below shows tensor with rank/degree 1 and 2

In [13]:
rank1 = tf.Variable(["One"], tf.string) # rank 1
rank2 = tf.Variable([['One','Two',"Six"],['Three','Four', 'Three']], tf.string) # rank 2

# check the ranks of these tensors
tf.rank(rank1), tf.rank(rank2)

(<tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

## Shape of Tensors

It is simply the amount of elements that exist in a dimension

In [16]:
rank2.shape # 2 lists and 3 elements in each

TensorShape([2, 3])

## Changing the Shape of Tensors

use tf.reshape(tensor,shape())

In [27]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[1,6])
tensor3 = tf.reshape(tensor2,[3,-1]) # placing -1 will automatically calculate the supposed value for the dimension of the tensor
                                     # hence that will be [3,2]

print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Type of Tensors

  - Variable
  - Constant
  - Placeholder
  - SparseTensor

  Except the Variable type, all other types are immutable. 

## Evaluating Tensors

Since Tensors represent partially complete computation, we would need to run what's called a *session* to evaluate the tensor

E.g:

    with tf.Session() as sess:
    tensor.eval()